# 日志
logging:
  config: classpath:logback-local.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: study
    password: study123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 60000

  mail:
    host: 127.0.0.1
    port: 10025
    username: demo-no-reply@gmail.com